apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "mpijob.name" . }}
    chart: {{ template "mpijob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "MPIJob"
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            app: "runaijob"
            project: {{ .Values.project }}
            {{- if .Values.user }}
            user: {{ .Values.user }}
            {{- end }}
        spec:
          nodeName: "gke-dev-3-gpu-pool-e0790631-djzk"
          schedulerName: runai-scheduler
          containers:
            - image: "{{ .Values.image }}"
              name: mpi
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              command:
                - mpirun
                - --allow-run-as-root
                - -np
                - "{{ .Values.workers }}"
                - -bind-to
                - none
                - -map-by
                - slot
                - -x
                - NCCL_DEBUG=INFO
                - -x
                - LD_LIBRARY_PATH
                - -x
                - PATH
                - -mca
                - pml
                - ob1
                - -mca
                - btl
                - ^openib
                - python
                - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
                - --model=resnet101
                - --batch_size=64
                - --variable_update=horovod
    Worker:
      replicas: {{ .Values.workers }}
      template:
        metadata:
          labels:
            app: "runaijob"
            project: {{ .Values.project }}
            {{- if .Values.user }}
            user: {{ .Values.user }}
            {{- end }}
        spec:
          schedulerName: runai-scheduler
          containers:
            - image: "{{ .Values.image }}"
              name: mpi
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              resources:
                limits:
                  nvidia.com/gpu: 1
